# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김한준
title: Java 백엔드 개발자
email: dhepd8849@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  khj1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile5.png
about_content: | # this will include new lines to allow paragraphs
  - 안녕하세요. 끊임없이 성장을 추구하는 개발자 김한준입니다.
  - 코드로 다양한 생각을 표현하는 과정에 매료되어 개발자를 꿈꾸게 되었습니다.
  - 지속적인 성장을 위해서는 <mark>꾸준함</mark>이 가장 중요하다고 생각하기에 깃허브에 학습한 내용을 정리하고 있습니다.
  - 현재 클린코드와 TDD에 관심을 갖고 공부중입니다.

content:
  - title: Skill 
    layout: list 
    content:
      - layout: left
        title: Backend
        description: | 
          - Java
          - Spring MVC, Spring Boot, Spring Security, Spring Data JPA, Spring Rest Docs
          - JPA, Querydsl, Hibernate
          - Junit5, Mockito
          - Gradle, Maven

      - layout: left
        title: Frontend
        description: | 
          - HTML5, CSS3, ES6, React
          - React, React-redux

      - layout: left
        title: DevOps
        description: | 
          - AWS - EC2, S3, RDS, CloudFront
          - MySQL, MariaDB, Oracle
          - Docker
          - Jenkins, Github-action

      - layout: left
        title: Collaboration & Tools
        description: | 
          - IntelliJ, Eclipse, VS Code
          - Git, Sourcetree

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 롤업
        link: https://github.com/khj1/lolup-backend-project
        quote: >
          KOSMO 82기 팀프로젝트입니다. 수료이후에도 꾸준히 리팩토링하고 있습니다.
        description: |
          - League of Legend 유저 매칭 시스템
          - [Riot API](https://developer.riotgames.com/apis)를 활용해 사용자들이 유저들의 정보를 명확하게 파악할 수 있도록 구현
          - 사용자간 커뮤니케이션은 간단한 채팅 기능을 통해 구현

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KOSMO 82기
        caption: 2021.03 - 2021.09
        sub_title: 오픈프레임워크 활용 디지털융합 SW엔지니어 양성과정 수료
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Java, Spring 기반 웹 개발에 필요한 전반적인 기본기 교육
          - 팀 프로젝트 진행

  - title: 현재 학습 내용과 추후 계획 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스트스텝 자바 플레이 그라운드
        link: https://edu.nextstep.camp/s/RFY359FE
        caption: 2021-10 ~ 진행중
        quote: >
          자바지기 박재성님 교육
        description: | # this will include new lines to allow paragraphs
          - TDD, OOP, 클린코드 교육

      - layout: left
        title: 패스트캠퍼스 AWS 인프라구축과 DevOps 운영
        link: https://fastcampus.co.kr/dev_online_awsdevops
        caption: 추후 학습 예정
        quote: >
          단계별로 구성된 AWS 인프라 구축과 DevOps 운영 교육
        description: | # this will include new lines to allow paragraphs
          - 개인 프로젝트 배포간, 막연하게 학습했던 DevOps 내용들을 명확하게 이해하기 위해 수강
          - 우선적으로 초급 단계 로드맵을 따라 학습할 예정입니다. 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
