# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김한준
title: Java 백엔드 개발자
email: dhepd8849@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  khj1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - 안녕하세요. 끊임없이 성장을 추구하는 개발자 김한준입니다.
  - 지속적인 성장을 위해선 <mark>꾸준함</mark>이 중요하다고 생각하기에 깃허브에 학습한 내용을 정리하고 있습니다.
  - 현재 저는 클린코드와 TDD에 관심을 갖고 공부중입니다.

content:
  - title: Skill 
    layout: list 
    content:
      - layout: left
        title: Backend
        description: | 
          - Java
          - Spring MVC, Spring Boot, Spring Security, Spring Data JPA, Spring Rest Docs
          - JPA, Querydsl, Hibernate
          - Junit5, Mockito
          - Gradle, Maven

      - layout: left
        title: Frontend
        description: | 
          - HTML5, CSS3, ES6, React
          - React, React-redux

      - layout: left
        title: DevOps
        description: | 
          - AWS - EC2, S3, RDS, CloudFront
          - MySQL, MariaDB, Oracle
          - Jenkins, Github-action

      - layout: left
        title: Collaboration & Tools
        description: | 
          - IntelliJ, Eclipse, VS Code
          - Git, Sourcetree

  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 롤업
        link: https://github.com/khj1/lolup-backend-project
        # link_text: Project Website
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KOSMO 82기
        caption: 2021.03 - 2021.09
        sub_title: 오픈프레임워크 활용 디지털융합 SW엔지니어 양성과정 수료
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Java, Spring 기반 웹 개발에 필요한 전반적인 기본기 교육
          - 팀 프로젝트 진행

  - title: 현재 학습 내용과 추후 계획 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스트스탭 자바 플레이 그라운드
        link: https://edu.nextstep.camp/s/RFY359FE
        sub_title: TDD, OOP, 클린코드 교육
        caption: 2021-10 ~ 진행중
        quote: >
          자바지기 박재성님 교육
        description: | # this will include new lines to allow paragraphs
          - 올바른 TDD와 클린코드 작성을 위해 수강중

  - title: 현재 학습 내용과 추후 계획 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스트스텝 자바 플레이 그라운드
        link: https://edu.nextstep.camp/s/RFY359FE
        sub_title: TDD, OOP, 클린코드 교육
        caption: 2021-10 ~ 진행중
        quote: >
          자바지기 박재성님 교육
        description: | # this will include new lines to allow paragraphs
          - 올바른 TDD와 클린코드 작성을 위해 수강

      - layout: left
        title: 패스트캠퍼스 AWS 인프라구축과 DevOps 운영
        link: https://fastcampus.co.kr/dev_online_awsdevops
        caption: 추후 학습 예정
        quote: >
          단계별로 구성된 AWS 인프라 구축과 DevOps 운영 교육
        description: | # this will include new lines to allow paragraphs
          - 개인 프로젝트 배포간 막연하게 학습했던 DevOps 내용들을 체화시키기 위해 수강
          - 우선적으로 초급 단계 로드맵을 따라 학습할 예정입니다. 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
